### ISSUE TITLE
How to use collection alias instead of the actual collection name in the Typesense adapter?

### ISSUE THREAD

**Issue by junelmujar** [typesense/typesense-instantsearch-adapter#103]
I might have missed it or I'm just looking at the wrong place but how do you use collection alias instead of the actual collection name when using the Typesense-instantsearch  adapter?

Any advice would be greatly appreciated.

Thanks!

**Comment by jasonbosco** [comment]
@junelmujar You can use a collection alias in any place you would have otherwise used a collection name. So for eg: 

```jsx
const search = instantsearch({
  searchClient,
  indexName: "collection-alias", // collection-alias can be used instead of collectionName
});
```

**Comment by junelmujar** [comment]
Thanks! That did the trick.
