### ISSUE TITLE
Can't access Typesense sorting metadata within a Hit component

### ISSUE THREAD

**Issue by everdrone** [typesense/typesense-instantsearch-adapter#109]
## Description

When sorting by `geopoint`, the distance from the point to the document location is not passed down into the `hit` object

## Steps to reproduce

- Integrate instantsearch with a geo-searchable collection
- sort by geo location

## Expected Behavior

The `hit` object should contain a reserved field for metadata that gets passed down from typesense, like the `text_match` score or the `geo_distance_meters` property

## Actual Behavior

Can't access the `geo_distance_meters` for each document

## Metadata

**Typsense Version**: 0.22.2

**OS**: macOS 12.3.1

**Comment by jasonbosco** [comment]
Great, thank you for confirming!
