### ISSUE TITLE
Hidden (permanent) filters don't get applied in vue-instantsearch during SSR

### ISSUE THREAD

**Issue by ArcoMul** [typesense/typesense-instantsearch-adapter#110]
## Description

I'm trying to specify certain (hidden) filters which always should be applied, no matter how the user adjusts other filters. In my case this is related to language and country settings.

I'm trying to do so using vue-instantsearch and server-side rendering.

This works correctly without SSR, but the server render doesn't display the right data.

## Steps to reproduce

This repo has a demo: https://github.com/ArcoMul/typesense-ssr-default-filters

Here I define that only songs from the 1960s decade should be shown: https://github.com/ArcoMul/typesense-ssr-default-filters/blob/master/src/main.js#L65

## Expected Behavior

When viewing the page with Javascript disabled (to see the server rendered data) songs from the 1960s should be shown

## Actual Behavior

Instead songs of 2920s are displayed.

## Metadata

typesense-instantsearch-adapter: 2.4.0
typesense: 1.2.2

**Comment by ArcoMul** [comment]
Not a fix, but a way to prevent this whole issue might be that typesense-instantsearch-adapter allows defining a separate `filter_by` value which always gets merged with the `filter_by` coming from InstantSearch.

Something like:

```js
const typesenseInstantsearchAdapter = new TypesenseInstantSearchAdapter({
  ...
  additionalSearchParameters: {
    query_by: "title",
    filter_by_override: 'release_decade:1960s'
  }
```

The on this line: https://github.com/typesense/typesense-instantsearch-adapter/blob/master/src/SearchRequestAdapter.js#L281 the two values could be merged in some way.

**Comment by jasonbosco** [comment]
@ArcoMul I'm not familiar enough with SSR in Vue... But along the lines of your idea, if your intention is for users to not be able to change the filter you want to programmatically apply, I'd recommend embedding it in a scoped search api key (on the server-side), and then using that scoped api key when instantiating the adapter: https://typesense.org/docs/0.22.2/api/api-keys.html#generate-scoped-search-key

**Comment by jasonbosco** [comment]
> Would then the best solution be to regenerate the api key? Would that even work to re-instantiate the adapter?

Yes, you would have to regenerate the scoped API key (on the server-side), and then reinstantiate the adapter with the new scoped API key and refresh the instantsearch widgets.

Separately, I just figured out what was happening in the demo repo you shared:

When you use the `filters` prop in the `Configure` widget, Algolia automatically ANDs those filters with the `facetFilters` that the `refinementList` (and related) widgets generate. This effectively gives you the ability to setup a fixed permanent filter.

I just added the ability for the adapter to handle the `filters` prop in addition to `facetFilters` and `numericFilters` in `v2.4.1-2`, so the behavior is similar to Algolia. [Here's](https://github.com/typesense/typesense-instantsearch-adapter#configure) documentation for the format to use with `filters`.

In previous versions, the `filters` prop was just ignored, so you had to use `facetFilters` with Typesense, but then Instantsearch overrides those `facetFilters` with the ones generated by the `refinementList` (and related) widgets once a user clicks on any of the items inside those widgets. 

Could you give `v2.4.1-2` a shot and let me know how it goes?

**Comment by ArcoMul** [comment]
This works perfect in `v2.4.1-3` @jasonbosco! Thanks a lot!

**Comment by jasonbosco** [comment]
Awesome, thank you for confirming!
