### ISSUE TITLE
Add option to bundle code manually

### ISSUE THREAD

**Issue by ArcoMul** [typesense/typesense-instantsearch-adapter#112]
## Description

I noticed that `regenerator-runtime/runtime.js` appears in our client-side JS bundle, which we don't need because we don't support IE11, and does add a significant amount of unnecessary JS. Would be great to have the option to bundle/compile the package ourselves so that our own bundle options can be used.

I'm by no means a npm package expert, so I might be wrong, maybe this is already possible in some way. Also not sure what the the solution would be, maybe if the src directory is also included when installing the package (by adding it to the `files` array in package.json) I could just include the files straight from that src directory? Or possibly the `module` option in package.json should be used which points to a version compiled without babel transformations.

## Metadata

`typesense: 1.3.0-6`

OS: Windows/Firefox

**Comment by jasonbosco** [comment]
@ArcoMul I'm also not an expert at npm packaging, but happy to include the `src` folder in the package if that helps. 

To verify this, could you clone this repo locally, use `npm link` and see if you're able to achieve what you have in mind by importing directly from `src`?

**Comment by FLevent29** [comment]
Moving all typesense js packages to pure ESM is the real and modern solution to this, I believe.
Angular for example gives warnings about CJS dependenices: https://angular.io/guide/build#configuring-commonjs-dependencies
Here's a good blog about the why (also linked int the Angular guide): https://web.dev/commonjs-larger-bundles/

**Comment by ArcoMul** [comment]
@jasonbosco I'm able to import `TypesenseInstantSearchAdapter` from the src folder, so including that folder would solve it in my case.

**Comment by ArcoMul** [comment]
@jasonbosco Would be great if you could release an update where the `src` folder is included? Would benefit us a lot! :-)

**Comment by jasonbosco** [comment]
@ArcoMul I've published [2.4.1](https://github.com/typesense/typesense-instantsearch-adapter/releases/tag/v2.4.1) with the `src` directory included.
