### ISSUE TITLE
can i set default sortby on InstantSearch?

### ISSUE THREAD

**Issue by kulame** [typesense/typesense-instantsearch-adapter#113]
## Description

i want to set default sortby  field on InstantSearch
and i try to use <Configure sort_by="xxx" /> it doesn't work.

how can i change the collectionSpecificSearchParameters  dynamic on TypesenseInstantSearchAdapter?

**Comment by jasonbosco** [comment]
@kulame Do you have a sortBy widget that users use? If so, the `sortBy` widget uses the first element in the `items` prop as the default one. 

If you don't have a user visible sort widget, you can use the `sort_by` parameter in additionalSearchParameters or `collectionSpecificSearchParameters`.

To make `collectionSpecificSearchParameters` dynamic, you want to reinstantiate the adapter with new settings each time.

**Comment by kulame** [comment]
got it., thanks

**Comment by emontes** [comment]
I have tryed to use the sort_by parameter in the typesenseInstantsearchAdapter like this:
```

additionalSearchParameters: {
    queryBy: 'title,description',
    filterBy: 'type: consejos',
    perPage: 8,
    sortBy: 'title',
  },
```

But I got the following error:
Error: 400 - Parameter `sort_by` is malformed.

What I'm doing wrong?

**Comment by jasonbosco** [comment]
You need to specify the sort order after the field name. So it should be title:asc or title:desc
