### ISSUE TITLE
Can we set default facet selected ?

### ISSUE THREAD

**Issue by KetanPansari** [typesense/typesense-instantsearch-adapter#115]
## Description
I am trying to select a facet whenever a user comes with a query-based URL. For e.g: <--website url-->/programs/?program=Course. Currently, I am using ais configure with facetFilter and disjunctive-facets-refinements.camel to prefilter the catalog. 

## Expected Behavior
The expected behavior should be just the facet should be selected and the result should be filtered. It should work like when we visit the main catalog and select a filter manually.

## Actual Behavior
What I am seeing is the catalog is filtering and the facet is getting selected but when I unselect the facet it does not go back to the default catalog. I tried removing the facet filter prop but now the disjunctive one works but it triggers once I start scrolling down(I have ais infinite scroll).

**Comment by jasonbosco** [comment]
@KetanPansari Could you put together a minimal example in codesandbox that replicates the issue? I can then help debug from there.

**Comment by ibasaw** [comment]
i try to do the same thing, i want on a specific url to get a pre filtered facet by brand

http://local/brand=xxx

i don't have the facet selected, and don't have it in the current refinements list

how to do this ?

**Comment by jasonbosco** [comment]
@ibasaw [Here's](https://www.algolia.com/doc/guides/building-search-ui/going-further/routing-urls/js/) a guide on how to manage URL routing with instantsearch.

**Comment by ibasaw** [comment]
yes i had founded it earlier :)
