### ISSUE TITLE
How to generate customize query using React Instant Search widget? 

### ISSUE THREAD

**Issue by shejal-Hauper-fe** [typesense/typesense-instantsearch-adapter#116]
## Description
I want to generate customize query as shown below:

{
    "searches": [
        {
            "query_by": "serverAddress",
            "sort_by": "",
            "highlight_full_fields": "serverAddress",
            "collection": "connections",
            "q": "10.9.91.27",
            "facet_by": "serverAddress",
            "max_facet_values": 100,
            "page": 1,
            "per_page": 100
        }
    ]
}

currently I am able to generate this type of query as shown in SS.  

![image](https://user-images.githubusercontent.com/103435307/174764000-c8b2566f-2d58-40c0-b02e-f9d380ffb14f.png)

but I don't know how to customize it as per my requirement. Currently I'm using ConnectRefinementList with typesense client.

**Comment by jasonbosco** [comment]
You can configure Typesense parameters using the `additionalServerParameters` key when instantiating the adapter like this: https://github.com/typesense/typesense-instantsearch-adapter#with-instantsearchjs

**Comment by shejal-Hauper-fe** [comment]
Thanks for quick help but how to change value for filter_by as shown below:
 `{
    "searches": [
        {
            "query_by": "serverAddress",
            "sort_by": "",
            "highlight_full_fields": "serverAddress",
            "collection": "connections",
            "q": "*",
            "filter_by":"serverAddress:=10.89.51.44",
            "facet_by": "serverAddress",
            "max_facet_values": 100,
            "page": 1,
            "per_page": 100
        }
    ]
}`

**Comment by jasonbosco** [comment]
The array syntax in filter_by also works with non-array fields. So this shouldn't throw an error.

**Comment by shejal-Hauper-fe** [comment]
Yes, it wouldn't throw any error but it doesn't allow user to trigger any query.

**Comment by shejal-Hauper-fe** [comment]
when we use facetFilters in <Configure> component all the facet counts get zero.
