### ISSUE TITLE
updateConfiguration missing

### ISSUE THREAD

**Issue by ribrdb** [typesense/typesense-instantsearch-adapter#120]
## Description

The last release says it added the updateConfiguration method, but I don't see the string 'updateConfiguration' in https://cdn.jsdelivr.net/npm/typesense-instantsearch-adapter@2.4.1/dist/typesense-instantsearch-adapter.min.js

**Comment by jasonbosco** [comment]
That method is still in the pre-release version: `2.4.2-1`
