### ISSUE TITLE
maxFacetHits ?

### ISSUE THREAD

**Issue by ibasaw** [typesense/typesense-instantsearch-adapter#125]
hi,

how to use the property maxFacetHits  ?

https://support.algolia.com/hc/en-us/articles/5588550618897-Clarifying-confusion-with-facets-facet-values-maxFacetHits-and-maxValuesPerFacet

i try to use but it always blocked at 10 results, i want to display more than 10 brands by exemple. 

https://www.algolia.com/doc/api-reference/api-parameters/maxFacetHits/

i use vuejs adapter on 2.4.1 version adapter

++

**Comment by jasonbosco** [comment]
The equivalent in Typesense is called `max_facet_values` and defaults to `10`. You can change it when instantiating the adapter like this:

```js
const typesenseInstantsearchAdapter = new TypesenseInstantSearchAdapter({
  server: {
    apiKey: "abcd", 
    nodes: [
      {
        host: "localhost",
        port: "8108",
        protocol: "http",
      },
    ],
  },
  additionalSearchParameters: {
    query_by: "field1,field2",
    max_facet_values: 20 // <=========================
  },
});
```

**Comment by ibasaw** [comment]
@jasonbosco i had already try this one and it seem not to be working

by exemple in my database i got 190 values, and it show only 10.

With typesense dashboard, this is doing the same thing, got only 10 values for each facet values

![2022-09-22_09-03](https://user-images.githubusercontent.com/313704/191754993-45b04494-99a5-45a4-8818-a4a34d49203f.png)
![2022-09-22_09-04](https://user-images.githubusercontent.com/313704/191754996-daa8b1aa-5f54-4406-9794-f867b6b4ed95.png)
![2022-09-22_09-04_1](https://user-images.githubusercontent.com/313704/191754997-9a899d48-1911-427a-9b11-5edcbe7b8ce5.png)

**Comment by jasonbosco** [comment]
Ah, it looks like you're using the refinementList widget. You can use the `limit` and `show-more-limit` props to control this behavior:

https://www.algolia.com/doc/api-reference/widgets/refinement-list/vue/#widget-param-limit
https://www.algolia.com/doc/api-reference/widgets/refinement-list/vue/#widget-param-show-more-limit

**Comment by ibasaw** [comment]
ok, thank you, i will try this soon

**Comment by ibasaw** [comment]
this is it ;)
