### ISSUE TITLE
AisStats get nbSortedHits with adapter ?

### ISSUE THREAD

**Issue by ibasaw** [typesense/typesense-instantsearch-adapter#127]
hi,

i use vuejs adapter on 2.4.1 version adapter.

Sorry for asking this.

how  can i get the state.nbHits from the component <ais-stats />  ?

![2022-10-04_17-16](https://user-images.githubusercontent.com/313704/193931011-05f047a6-7160-4bec-8fd6-fcd97eb8280a.png)

in my vue file, i just want to get the number of results to do like this
```
<div v-if='nbHits > 0'>something</div>
<div v-else>sorry no result</div>
```

**Comment by jasonbosco** [comment]
@ibasaw Here's the code snippet to access nbHits in `ais-stats`: https://www.algolia.com/doc/api-reference/widgets/stats/vue/#scope

```vue
<ais-stats>
  <template v-slot="{ hitsPerPage, nbPages, nbHits, page, processingTimeMS, query }">
    Page {{ page + 1 }} of {{ nbPages }} with {{ hitsPerPage }} hits per page  -
    {{ nbHits }} hits retrieved in {{ processingTimeMS }}ms for <q>{{ query }}</q>
  </template>
</ais-stats>
```

**Comment by ibasaw** [comment]
@jasonbosco i need to get the nbHits outside the ais-stats template component.
i don't want to customize or extend the ais-stats. No need to display the stats, just need the prop : nbHits to render my html conditionnaly.

**Comment by jasonbosco** [comment]
Ah, then you probably want to use this headless widget: https://www.algolia.com/doc/api-reference/widgets/state-results/vue/#about

**Comment by ibasaw** [comment]
@jasonbosco thank you !
