### ISSUE TITLE
Disjunctive facets

### ISSUE THREAD

**Issue by mindtechmedia** [typesense/typesense-instantsearch-adapter#13]
## Description

I am not able to get disjunctive facets (https://community.algolia.com/algoliasearch-helper-js/reference.html#disjunctive-facets) to work

## Steps to reproduce
This is the code I am using with the books mapping:
```
search.addWidgets([
    configure({
        "disjunctiveFacets": [
            "authors_facet"
        ]}),
```
## Expected Behavior

I would like to filter on the authors and then when I select author A , with disjunctiveFacet being authors_facet, I would expect that the facet only displays authors that have written a book **together** with author A

## Actual Behavior
All authors are being shown in the facet

With a facet being added to the disjunctiveFacet array, users should be able to find a book that has the categories romance **AND** action. Currently selecting romance and action shows either romance **OR** action books

**Comment by jasonbosco** [comment]
@mindtechmedia Disjunctive facets are `OR`ed by definition. Here's an example from the link you shared above:

```javascript
// helper is already configured
helper.addDisjunctiveFacetRefinement('tech', 'crt');
helper.addDisjunctiveFacetRefinement('tech', 'led');
helper.addDisjunctiveFacetRefinement('tech', 'plasma');

// the filters are equals to
// tech = crt OR tech = led OR tech = plasma
```

Notice how it's `tech = crt OR led OR plasma` when you do `addDisjunctiveFacetRefinement`

If you're looking to do AND, you want to use Conjunctive facets: https://community.algolia.com/algoliasearch-helper-js/reference.html#conjunctive-facets

Let me know if I've misunderstood anything.

**Comment by jasonbosco** [comment]
Closing this for now, but please feel free to reopen if you still have issues.
