### ISSUE TITLE
How to set curation via overrides?

### ISSUE THREAD

**Issue by amamenko** [typesense/typesense-instantsearch-adapter#132]
Hi, I would like to set Typesense collection overrides using this library as detailed in the [Typesense curation docs](https://typesense.org/docs/0.23.1/api/curation.html#create-or-update-an-override) for version 0.23.1.

Typesense's docs show an example as such:
```js
client.collections('companies').overrides().upsert('customize-apple', override)
```

I tried to follow their lead using the `typesense-instantsearch-adapter` library like so:
```js
typesenseInstantsearchAdapter.typesenseClient.collections('companies').overrides().upsert('customize-apple', override)
```
but I get the error
```
typesenseInstantsearchAdapter.typesenseClient.collections(...).overrides is not a function
```

so `typesenseInstantsearchAdapter.typesenseClient.collections('companies')` does indeed exist, but the `overrides` method does not.

Are overrides supported by this library at the moment and, if so, is there any documentation on how to set them up?

**Comment by jasonbosco** [comment]
@amamenko `typesenseInstantsearchAdapter.typesenseClient` is actually the [`SearchClient`](https://github.com/typesense/typesense-js/blob/b0854ab5829b6819e82b6fa9d3304643b9d0772e/src/Typesense/SearchClient.ts) from the Typesense JS / TS library, which only supports searching and no other operations.

So to access overrides, you want to instantiate a separate `Client` object from the Typesense JS/TS library.
