### ISSUE TITLE
Can I call the searchClient.Search method in react.js?

### ISSUE THREAD

**Issue by premmadellkumar** [typesense/typesense-instantsearch-adapter#137]
## Description

I am trying to call the searchClient.Search() method in react.js file. I get the error as 'Unhandled Rejection (TypeError): Cannot read properties of undefined (reading 'map')'

## Steps to reproduce
![image](https://user-images.githubusercontent.com/121602259/209918214-663f9c0e-f58d-4baf-bfe8-ac67a6d47080.png)

**Comment by jasonbosco** [comment]
Could you post the full code snippet that throws this error? 

Also, could you expand on what you're looking to do by calling this method directly? Typically, Instantsearch calls this method internally, so you don't have to call it directly.

**Comment by premmadellkumar** [comment]
Hi Jason, Thank you for replying. I got rid of this issue. I am trying to continuously update the data displayed. Is there any other better way to do this?

Thanks and regards,
Prem

**Comment by jasonbosco** [comment]
May be this is helpful to refresh the data continuously: https://stackoverflow.com/questions/71668510/how-to-force-refresh-on-react-instant-search-dom-in-algolia-or-fetch-updated-dat

**Comment by premmadellkumar** [comment]
Thank you. That helps.

Regards,
Prem
