### ISSUE TITLE
Dynamically load additional search parameters / query by

### ISSUE THREAD

**Issue by ashwinmram** [typesense/typesense-instantsearch-adapter#14]
I'd like to start off by saying a big THANK YOU :) for making it so simple to swap out the awesome Instantsearch library with Typesense via this adaptor.  I was praying there was such a solution last week and yesterday I discovered both Typesense and your adaptor.  I was afraid that most of the money earned through my app when the record size grows will be paid to Algolia, but now that is no longer a concern!

## Description

I am using Vue Instantsearch and have defined the search client in my root Vue component.  The problem I am facing is that the queryBy search parameters will change for each model and I'm not sure how to swap this out dynamically.

## More Details

```
const typesenseInstantsearchAdapter = new TypesenseInstantSearchAdapter({
  server: {
    apiKey: "api-key", 
    nodes: [
      {
        host: "hostname",
        port: "443",
        protocol: "https"
      }
    ]
  },
  
  additionalSearchParameters: {
    queryBy: "full_name,last_name,first_name,"
  }
});
const searchClient = typesenseInstantsearchAdapter.searchClient;

const app = new Vue({
   el: '#app',

   data() {
     return {
       searchClient
     };
   },
```

On my model specific page I call the component as below:

```
  <ais-instant-search
    :search-client="searchClient"
    index-name="guests"
  >
```

My challenge is if I define a universal searchClient like I previously did with Algolia's search client I am unsure how to dynamically define the query by search parameters.  With Algolia this was not required.

I tried definiing all the fields across all my models on the global searchClient but when the document does not have that search field it throws an error, which makes sense of course.

I'd appreciate some help on this!  

## Metadata

**Typsense Version**: v0.17.0 / Typesense Cloud

**OS**: MacOS Catalina 10.15.7

**Comment by jasonbosco** [comment]
Hi @ashwinmram! I'm glad you found Typesense :)

re: your question, you should be able to declare multiple instances of `typesenseInstantsearchAdapter`, each one configured with a different `queryBy` value and use the corresponding searchClient in each model. 

So going off of your example, it would be something like this:

```
const typesenseServerConfig = {
  apiKey: "api-key", 
  nodes: [
    {
      host: "hostname",
      port: "443",
      protocol: "https"
    }
  ]
}

const typesenseInstantsearchAdapterForModelX = new TypesenseInstantSearchAdapter({
  server: typesenseServerConfig,
  additionalSearchParameters: {
    queryBy: "full_name,last_name,first_name,"
  }
});
const searchClientForModelX = typesenseInstantsearchAdapterForModelX.searchClient;

const typesenseInstantsearchAdapterForModelY = new TypesenseInstantSearchAdapter({
  server: typesenseServerConfig,
  additionalSearchParameters: {
    queryBy: "field_a,field_b"
  }
});
const searchClientForModelY = typesenseInstantsearchAdapterForModelY.searchClient;

const app = new Vue({
   el: '#app',

   data() {
     return {
       searchClientForModelX,
       searchClientForModelY
     };
   },
```

```
<ais-instant-search
    :search-client="searchClientForModelX"
    index-name="guests"
  >
```

```
<ais-instant-search
    :search-client="searchClientForModelY"
    index-name="another_index"
  >
```

Does that work?

**Comment by ashwinmram** [comment]
Hi Jason, that will definitely work.  It does require repetition for each model but that is far from a deal breaker.  I will just do this.  I'm going to close this :)  In the ideal scenario if you can figure out a way for the queryBy to automagically figure out what are all the available queryBy fields from the document, then you won't need to hard code it here.  You have more important stuff to work on, so don't worry about this further.  Thanks a bunch!

**Comment by ashwinmram** [comment]
To those of you reading this and in order to avoid duplication I did the following:

1.  Create a generic component to use in my views

```
<template>
  <div>
    <slot v-bind:searchClient="searchClient"></slot>
  </div>
</template>

<script>
import TypesenseInstantSearchAdapter from "typesense-instantsearch-adapter";

export default {
  props: ['queryBy'],

  data() {
    return {
      typesenseInstantsearchAdapter: '',
      searchClient: ''
    }
  },

  created() {
    this.typesenseInstantsearchAdapter = new TypesenseInstantSearchAdapter({
      server: {
        apiKey: "typsesense-apikey", // Be sure to use the search-only-api-key
        nodes: [
          {
            host: "hostname",
            port: "443",
            protocol: "https"
          }
        ]
      },
      // The following parameters are directly passed to Typesense's search API endpoint.
      //  So you can pass any parameters supported by the search endpoint below.
      //  queryBy is required.
      additionalSearchParameters: {
        queryBy: this.queryBy
      }
    });

    this.searchClient = this.typesenseInstantsearchAdapter.searchClient;
  }
}
</script>
```

I then slipped in the query by parameters as a prop and pulled up the searchClient using object destructuring like this:

```
<model-index v-slot="{ searchClient }"
  query-by="full_name,last_name,first_name"
>
  <ais-instant-search
    :search-client="searchClient"
    index-name="guests"
  >
  // ...
  </ais-instant-search>
</model-index>
```
