### ISSUE TITLE
Highlighting nested fields doesn't work / is unreliable

### ISSUE THREAD

**Issue by philefstat** [typesense/typesense-instantsearch-adapter#144]
## Description

Typesense correctly identifies matches in nested fields and adds them to the "highlight" array in results, however that same highlight is then marked as "matchLevel: none" in the `_highlightResult` of the adapted results.

## Steps to reproduce

- Schema with nested fields, in this case the field is  of relevance is
```       
{
          name: "assets.subtypeStationary",
          type: "string[]" as FieldType,
          optional: true,
          facet: true,
        },
```

- Frontend search using vue-instantsearch 4.8.2 and typesense-instantsearch-adapter 2.5.0

- Search query "Business Card"

- Typesense API response in network, showing a specific "asset":

<img width="722" alt="Screenshot 2023-02-08 at 15 21 31" src="https://user-images.githubusercontent.com/9018494/217579046-0bc6a0cf-6c0b-4d4c-8023-9a9cc52ac411.png">

Same "asset" shown in algolia results:
<img width="325" alt="Screenshot 2023-02-08 at 15 22 44" src="https://user-images.githubusercontent.com/9018494/217579314-d97a66df-28fe-456f-8fdd-1616ffb9ded9.png">

- However, in the same exact set of results, it does work in some cases:

<img width="705" alt="Screenshot 2023-02-08 at 15 22 00" src="https://user-images.githubusercontent.com/9018494/217579472-9028883c-7de8-4334-acc0-8ecf5f783c91.png">

<img width="476" alt="Screenshot 2023-02-08 at 15 23 27" src="https://user-images.githubusercontent.com/9018494/217579555-2766b767-ed27-4ad9-90bd-6d91ec5e2992.png">

## Expected Behavior

Highlighted nested fields from the typesense response are transformed into highlights for use in instantsearch

## Actual Behavior

Some highlights are transformed correctly, but others which have match level "full" in the typesense response have match level "none" in the transformed instantsearch results

## Metadata

**Typesense Version**: 0.24

**OS**: macOS 12.0.1

---

My naive question, not having dug too much in this package is how does the adapter match specific highlighted nested fields given they don't include an id or index field in the top level `highlight` result from the server?

Sorry if this isn't clear

**Comment by jasonbosco** [comment]
@philefstat For a given hit in the results, the `highlight` is a sibling key to `document` and only contains the highlights for that document. 

Could you share your typesense-instantsearch-adapter configuration and also the full JSON results returned by Typesense? I can then try to trace this locally to see what's going on.

**Comment by philefstat** [comment]
@jasonbosco thanks for your quick response. 

here's a subset of the schema:

```js
{
    schema: {
      name: "identities",
      fields: [
        { name: "id", type: "string" as FieldType },
        { name: "name", type: "string" as FieldType },
        {
          name: "assets",
          type: "object[]" as FieldType,
          optional: true,
        },
        {
          name: "assets.subtypeStationary",
          type: "string[]" as FieldType,
          optional: true,
          facet: true,
        },
        { name: ".*", type: "auto" as FieldType },
      ],
      enable_nested_fields: true
    }
```

Here's an example document:
```json 
{
  "articles": [
    {
      "content": "..."
    }
  ],
  "assets": [
    {
      "imageId": "image-2eb75a6fd1a41610f712f5663d92295b001da8e2-900x597-jpg",
      "subtypeLogo": [
        "Combined Mark"
      ],
      "type": [
        "Logo"
      ]
    },
    {
      "imageId": "image-cc2f95eba073c75248d886746c2a0836441001db-900x578-jpg",
      "subtypeApplication": [
        "Stationary"
      ],
      "subtypeStationary": [
        "Business Card"
      ],
      "type": [
        "Brand application"
      ]
    },
    {
      "imageId": "image-df885b54cfdd3b706555f354d867920db74f5d24-900x578-jpg",
      "subtypeApplication": [
        "Stationary"
      ],
      "type": [
        "Brand application"
      ]
    },
    {
      "imageId": "image-3031c66005df7696ed887c8251c52940789512af-900x578-jpg",
      "subtypeApplication": [
        "Packaging"
      ],
      "type": [
        "Brand application"
      ]
    },
    {
      "imageId": "image-86a806627b84814130fc4715fe202be5f30c2ddd-900x578-jpg",
      "subtypeApplication": [
        "Packaging"
      ],
      "type": [
        "Brand application"
      ]
    },
    {
      "imageId": "image-33a6a106b0e631caaf28200f8e9ec94f025027c6-900x578-jpg",
      "subtypeApplication": [
        "Packaging"
      ],
      "type": [
        "Brand application"
      ]
    },
    {
      "imageId": "image-d46a04644c7a283f2ef50f144269a1c6247d513c-900x578-jpg",
      "subtypeApplication": [
        "Packaging"
      ],
      "type": [
        "Brand application"
      ]
    },
    {
      "imageId": "image-590f621b6c7087abbe1411da799ccb01eaa434d3-900x578-jpg",
      "subtypeApplication": [
        "Signage"
      ],
      "type": [
        "Brand application"
      ]
    }
  ],
  "client": {
    "name": "Foo"
  },
  "id": "9937",
  "name": "Bar",
  "year": 2011
}
```

Note that I use `string[]` instead of string for all the "subtype" fields because it throws an error if they are just "string" since they are in a nested object[]

The search configuration I am using is while debugging:
```json 
{
  "query_by": "name,assets.subtypeStationary",
   "highlight_full_fields": "assets.subtypeStationary"
}
```
and the example query I use is "Business card"

The resulting "highlight" under "hit" for the document in results looks like this:
```json
{
  "highlight": {
    "assets": [
        {
          "subtypeStationary": [
            {
              "matched_tokens": [
                "Business",
                "Card"
              ],
              "snippet": "<mark>Business</mark> <mark>Card</mark>",
              "value": "<mark>Business</mark> <mark>Card</mark>"
            }
          ]
        }
      ]
    }
}
```


I think the issue is that in the returned `highlight` for the document there is only one returned item in "assets" and no index to match it with the specific "asset". Digging into the code a bit, I think this is related to `_adaptHighlightInArrayValue` in `searchResponseAdapter`, but it also may be that the server needs to return an indice to identify which of the nested objects the highlight relates to.

Hope this information is helpful.

**Comment by jasonbosco** [comment]
@philefstat Thank you for sharing that. It turns out that this is actually due to a bug in how we handle nested field highlights in v0.24 - in an array of objects, we skip over any objects that don't have any highlights. We have a potential fix for this in 0.24.1.rc3. You should find a DEB and Docker image for it. Could you upgrade to it and let me know if the issue still persists?

**Comment by philefstat** [comment]
@jasonbosco apologies for the delay. I've tested it and it works now, thanks very much for the quick fix!!!

**Comment by jasonbosco** [comment]
Awesome, thank you for helping catch this issue!
