### ISSUE TITLE
Make host/port/protocol in nodes[] optional if url provided

### ISSUE THREAD

**Issue by carderne** [typesense/typesense-instantsearch-adapter#159]
## Description
If `url` is provided, `protocol`, `host`, `port` and `path` aren't needed.
They are passed to [this code in typesense-js](https://github.com/typesense/typesense-js/blob/1badf3385ca97711d6f86900fd0ca3b736cc63cf/src/Typesense/ApiCall.ts#L299-L304).

## Steps to reproduce
```js
  const typesenseInstantSearchAdapter = new TypesenseInstantSearchAdapter({
    server: {
      nodes: [
        {
          url: "http://localhost:8108",
          host: "",
          port: 0,
          protocol: "",
        },
      ],
...
```

## Expected Behavior
This code works. The types just need updating.

## Metadata
**Typesense Version**: `1.5.2`

**Comment by jasonbosco** [comment]
Could you try this out in `2.7.0-4` and let me know?
