### ISSUE TITLE
ais-configure filters not working as expected

### ISSUE THREAD

**Issue by ashwinmram** [typesense/typesense-instantsearch-adapter#16]
## Description

This adapter works like magic except I'm not sure how to apply filters that are not part of a refinement list but applied immediately.  Is there any way to feed in some filters into the search client the way we do the additionalSearchParameters via the queryBy field?

## Steps to reproduce

I used the following code and have configured the status as a facet but the filter is not getting applied.

```
public function getCollectionSchema(): array {
    return [
        'name' => 'reservations',
        'fields' => [
            // ...
            [
                'name' => 'hotel_id',
                'type' => 'int32',
                'facet' => true
            ],
            [
                'name' => 'status',
                'type' => 'string',
                'facet' => true
            ]
        ],
        'default_sorting_field' => 'hotel_id'
      ];
    }
```

```
<ais-instant-search
    :search-client="searchClient"
    index-name="reservations"
  >
    <ais-configure
          filters="hotel_id:1 AND status:checked_in OR status:due_out"
    ></ais-configure>
    // ...
```

## Expected Behavior

I expect that the rendered list should be filtered to only display the status of checked_in and due_out. 

## Actual Behavior

No filters are being applied.

## Metadata

**Typsense Version**: v0.17.0

**OS**: MacOS 10.15.7

**Comment by jasonbosco** [comment]
@ashwinmram Could you try this:

```jsx
<ais-instant-search
    :search-client="searchClient"
    index-name="reservations"
  >
    <ais-configure
          :facet-filters="hotel_id:1 AND status:[checked_in,due_out]"
    ></ais-configure>
    // ...
```

**Comment by ashwinmram** [comment]
@jasonbosco  I'm afraid it didn't work.  Even if I try to filter by status:checked_in only, it doesn't filter.

**Comment by ashwinmram** [comment]
I did a lit bit of a source dive just now and uncommented the following in your SearchRequestAdapter.js

```
console.log(params);
console.log(typesenseSearchParams);
```

The params received from the <ais-configure> component are being captured by the Javscript.

Console log `params` output:

```
{
   facets: array(6),
   filters: hotel_id:1 AND status:['checked_in','due_out'],
   query: "",
   tagFilters: "",
   page: 0,
   maxValuesPerFacet: 10
}
```

`typesenseSearchParams` output:

```
{
    facet_by: "... stringified version of facets array above ...",
    filter_by: "",
    highlight_full_fields: "... all the queryBy fields ... ",
    max_facet_values: 10,
    page: 1,
    q: "*",
    query_by: ".. all the queryBy fields ... ",
    sort_by: undefined
}
```

I tried changing my ais-configure from `filters="..."` to `facet-filters="..."` as well as `facetFilters="..."` but I didn't see any change to the transformed search parameters.

I saw you transform facet filters but not regular filters in your code.

I then read this to see the difference:
https://www.algolia.com/doc/guides/managing-results/refine-results/filtering/in-depth/filters-and-facetfilters/

I then changed my code to:

```
<ais-configure
      facet-filters="[hotel_id:1,[status:checked_in, status:due_out]]"
></ais-configure>
```

The filter_by is still not being populated on the `typesenseSearchParams`

The below is not working either.  Not sure what is the issue...

```
<ais-configure
      facetFilters="[hotel_id:1,[status:checked_in, status:due_out]]"
></ais-configure>
```

**Comment by jasonbosco** [comment]
@ashwinmram Thank you for the detailed investigation! I played around with a sample Vue-InstantSearch app and was able to identify a potential solution. Like you also found out, the key is to define the `AND` and `OR` in [this format](https://www.algolia.com/doc/api-reference/api-parameters/facetFilters/?client=javascript):

```javascript
[
  'attribute:value', // (single string)

  // attribute1:value AND attribute2:value (multiple strings)
  'attribute1:value', 'attribute2:value'

  // attribute1:value OR attribute2:value (multiple strings within an array)
  ['attribute1:value', 'attribute2:value'],

  // (attribute1:value OR attribute2:value) AND attribute3:value (combined strings and arrays)
  ['attribute1:value', 'attribute2:value'], 'attribute3:value',

  ...
]
```

And then on Vue side, you need to use `.camel` after the parameter name like this:

```vue
<ais-configure
          :facet-filters.camel="['hotel_id:1', ['status:checked_in', 'status:due_out']]"
    ></ais-configure>
```

I was able to get `ais-configure` to work this way in my sample app. Let me know if it doesn't work, and I can put up my sample app on a github repo and share it with you.

**Comment by ashwinmram** [comment]
You da man!!!  That worked like a charm 😃👏🏽🙏🏽 

```
<ais-configure
      :facet-filters.camel="['hotel_id:1',['status:checked_in','status:due_out']]"
></ais-configure>
```

Thanks a lot, Jason!
