### ISSUE TITLE
Could not parse the filter query when query contains parentheses

### ISSUE THREAD

**Issue by dziugas-liaudinskas** [typesense/typesense-instantsearch-adapter#165]
## Description

Hello,
I'm using instantsearch `Configure` widget to define category pages. It is used as this:
```
const filters = 'hierarchicalCategories.lvl2:"Audio > Home Audio > Speakers"';
...
<Configure filters={filters} />
```

(you can see working example [here](https://codesandbox.io/p/github/dziugas-liaudinskas/algolia-example/working-example?file=%2Fapp%2Fcomponents%2FSearch.tsx&selection=%5B%7B%22endColumn%22%3A5%2C%22endLineNumber%22%3A63%2C%22startColumn%22%3A5%2C%22startLineNumber%22%3A63%7D%5D&layout=%257B%2522activeFilepath%2522%253A%2522%252Fapp%252Fcomponents%252FSearch.tsx%2522%252C%2522openFiles%2522%253A%255B%2522%252Fapp%252Fcomponents%252FSearch.tsx%2522%252C%2522%252Fapp%252Froutes%252Fcategory%252F%2524slug.tsx%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522fullScreenDevtools%2522%253Afalse%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522vertical%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522DEVTOOLS_PANELS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522clh0fik5j00093b6lsy1vh9v4%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clh0fik5j00093b6lsy1vh9v4%2522%253A%257B%2522id%2522%253A%2522clh0fik5j00093b6lsy1vh9v4%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clh0filqe00743b6l1u8i7qan%2522%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A8002%252C%2522id%2522%253A%2522clh0fipiv00bd3b6l6itabhnn%2522%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clh0fir3100de3b6lrh08bmsm%2522%252C%2522path%2522%253A%2522%252Fcategory%252Fspeakers%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clh0fir3100de3b6lrh08bmsm%2522%257D%257D%252C%2522showSidebar%2522%253Atrue%252C%2522showDevtools%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%252C%2522editorPanelSize%2522%253A36.441798941798936%252C%2522devtoolsPanelSize%2522%253A46.44179894179894%257D). In `/app/routes/category/$slug.tsx` line 14 I define filters and in `/app/components/Search.tsx` line 92 I use it).

In this case, everything works as expected but if the category contains parentheses (eg `hierarchicalCategories.lvl2:"Audio > Home Audio > Speakers (100DB)"`) then I get `400 - Could not parse the filter query`.  Sorry that I don't have a reproducible case with a typesense adapter.

```Error: 400 - Could not parse the filter query.
    at TypesenseInstantsearchAdapter._validateTypesenseResult (/node_modules/typesense-instantsearch-adapter/src/TypesenseInstantsearchAdapter.js:86:13)
    at map (/node_modules/typesense-instantsearch-adapter/src/TypesenseInstantsearchAdapter.js:26:14)
    at Array.map (<anonymous>)
    at TypesenseInstantsearchAdapter._callee$ (/node_modules/typesense-instantsearch-adapter/src/TypesenseInstantsearchAdapter.js:25:58)
    at tryCatch (/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:125:22)
    at Generator.next (/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:9)
    at runMicrotasks (<anonymous>)
```

**Typesense Version**:
```
"typesense": "^1.5.3",
"typesense-instantsearch-adapter": "^2.6.0-1"
```

**Comment by jasonbosco** [comment]
`filters` should be in the Typesense format for `filter_by` described [here](https://typesense.org/docs/0.24.1/api/search.html#filter-parameters). 

So this line of code should be:

```js
const filters = 'hierarchicalCategories.lvl2:=`Audio > Home Audio > Speakers`';
```

**Comment by dziugas-liaudinskas** [comment]
That solved the issue. Thanks!
