### ISSUE TITLE
Add infix parameter

### ISSUE THREAD

**Issue by carderne** [typesense/typesense-instantsearch-adapter#168]
## Description
I'm using Typesense's `infix` feature but can't see a way to use it with the adapter.

## Expected Behavior
Would expect the parameters to look something like this (copying from README):
```js
  additionalSearchParameters: {
    query_by: "name,description,categories",
    infix: "always,off,fallback",
  },
```

**Comment by jasonbosco** [comment]
That should work... Did you run into any issues? If so, could you share the error you see?

**Comment by carderne** [comment]
Sorry I must have got confused between trying infix and preset.

I grep'd for `infix` in the repo and didn't find anything so assumed (incorrectly) that I wasn't being stupid. :)

**Comment by jasonbosco** [comment]
The types for the search params mostly come directly from `typesense-js` which is why this adapter repo doesn't have the word `infix` in it.
