### ISSUE TITLE
Correctly type `preset` parameter

### ISSUE THREAD

**Issue by carderne** [typesense/typesense-instantsearch-adapter#169]
## Typing issue
The `additionalSearchParameters` or `collectionSpecificSearchParameters` appears to accept a `preset` parameter to use Typesense [Presets](https://typesense.org/docs/0.24.0/api/search.html#presets).
But if I try:
```typescript
    collectionSpecificSearchParameters: {
      collection_a: {
        preset: "preset_1",
      },
      collection_b: {
        preset: "preset_2",
      },
```

**Comment by carderne** [comment]
Sorry didn't realise how fresh this is even in `typesense-js`!

**Comment by jasonbosco** [comment]
@carderne I just published `v2.7.0-5`. Could you upgrade to it and see if that fixes the typing issue?

**Comment by carderne** [comment]
I'm still getting 
```
Property 'query_by' is missing in type '{ preset: string; }' but required in type 'SearchParametersWithQueryBy'
```

**Comment by jasonbosco** [comment]
Ah I missed a spot. Could you check in `v2.7.0-6`.

**Comment by carderne** [comment]
Yup, working now!
