### ISSUE TITLE
Making the sort by reactive

### ISSUE THREAD

**Issue by aljabr** [typesense/typesense-instantsearch-adapter#179]
Hi,

I am trying to make new search after changing the sortby location to the new location lng lat with 
vue instantsearch

but there is no events to re trigger the search and even updating the search params will not work since it’s coming from outside the component

i spent days trying to resolve this issue with no luck

Thank you

**Comment by jasonbosco** [comment]
The typesense-instantsearch-adapter is stateless and does not initiate any search requests by itself. 

So instead, you would have to get vue to reinstantiate all the widgets which will then retrigger a search and then the new sort by value will be used on the next search. 

You might want to for eg, set a key on the ais-instantsearch widget that uses the sort by value, so when the sort by value changes, the key changes and the ais-instantsearch widget and all the child objects are re-rendered.
