### ISSUE TITLE
facetByOptions per collection, rather than universally

### ISSUE THREAD

**Issue by pixelmaven** [typesense/typesense-instantsearch-adapter#190]
## Description

I have two indexes that share a field name, but would like to sort the facets in one and not the other. Currently I can set this globally in the typesense adapter config.

Perhaps this should be treated similarly to `collectionSpecificSearchParameters` instead, to allow for collection specific `facetByOptions` configuration.

## Steps to reproduce

```
facetByOptions: {
	brand: '(sort_by: _alpha:asc)',
},
```

## Expected Behavior

```
collectionSpecificFacetByOptions: {
	products: {
		brand: '(sort_by: _alpha:asc)',
	}.
},
```

## Actual Behavior

Globally configured/sorted facet lists, rather than collection specific.

## Metadata

**Typesense Version**: `typesense/typesense:0.26.0.rc41`
`typesense-instantsearch-adapter@2.8.0-1`
`typesense@1.7.2`

**Comment by jasonbosco** [comment]
@pixelmaven Just added the ability to specify `collectionSpecificFacetByOptions` in `v2.8.0-4`. Could you give it a shot and let me know how it goes?

**Comment by pixelmaven** [comment]
@jasonbosco Looks good on my end, thanks!

**Comment by jasonbosco** [comment]
Awesome, thank you for confirming and thank you for catching this!
