### ISSUE TITLE
Issue with filter_by parameters when using facets

### ISSUE THREAD

**Issue by alexgvozden** [typesense/typesense-instantsearch-adapter#196]
## Description

If you set filterBy in the search configuration and use facet filtering with RefinementList, the facet filter overwrites (ignores) filterBy configuration which results in more results

## Steps to reproduce

For example if I filter all results by default from config with filterBy
 additionalSearchParameters: {
    queryBy: "embeddings,title",
    vectorQuery: `embeddings:([], distance_threshold:0.1)`,
    perPage: 10,
    filterBy: "score:>6",
  },

and than use facets with 

<RefinementList attribute="mentions" />

Than request made to server will contain filterBy score, but if I click one of the refinement options facets, than filterBy score is ignore and overwritten by facet filterBy option.

## Expected Behavior

Filtering by facet should not ignore and overwrite configured filterBy parameter. 

## Actual Behavior

Filtering by facet overwrites filter_by parameter in request and only uses facets filter

## Metadata

Typesense 0.25.2

Mac OSX

**Comment by alexgvozden** [comment]
I have fixed this issue and prepare pull request. Please test and merge if that is ok so in next release it's included.
Thank you

**Comment by jasonbosco** [comment]
Thank you for the PR, it's an interesting way to solve this. 

But, there is actually already a way to setup fixed filter from within Instantsearch: https://github.com/typesense/typesense-instantsearch-adapter/issues/17#issuecomment-876758570

**Comment by alexgvozden** [comment]
Hi, thank you for your answer

If I understand correctly than filter_by is meant to be removed even if it's specified in initial search paramters?

example there is about adding a facet helpr, while I have an issue with filter_by property being removed (not for facet but score, which is just a field)

I will try to find if using searchFunction can help for that and what are the function but I see searchFunction is depreceted and onStateChange should be used.

if you can help me understand how to retaing filter_by without changing the code of the library it woudl be great

**Comment by jasonbosco** [comment]
> If I understand correctly than filter_by is meant to be removed even if it's specified in initial search paramters?

That's correct. This is how the InstantSearch library works when used without Typesense. You'd typically use the `configure` widget to setup default search parameters, and then the other filter widgets will override the default parameters. 

> example you provided is about adding a facet helpr, while I have an issue with filter_by property being removed (not for facet but score, which is just a field)

It's a facet refinement, which is how Instantsearch calls filtering. 

> searchFunction is depreceted and onStateChange should be used

I'm not familiar with this deprecation, but if you look at Instantsearch / Algolia forums on how to setup a fixed a fixed filter, you should find the latest way to do this from within Instantsearch.

**Comment by alexgvozden** [comment]
Thank you!

**Comment by alcohol** [comment]
I'm using `filter_by: "id:* || $collection(id: *)"` as a means to create a [left join](https://typesense.org/docs/27.1/api/joins.html#left-join) on another collection; however this `filter_by` value is lost on the additional searches generated the moment I start narrowing down the search using the refinement (facet) widgets. It is unclear to me how I can setup a fixed filter on something that isn't actually a facet. Should I open a new issue for this or is this issue still relevant?

**Comment by jasonbosco** [comment]
Instantsearch manages the life cycle of filters. So you want to set filters inside of the Instantsearch framework as described here: https://github.com/typesense/typesense-instantsearch-adapter/issues/17#issuecomment-876758570

**Comment by alcohol** [comment]
It took some diving in the actual code and documentation, but I managed to figure it out. Thanks.

We're using instantsearch, and in the end I simply had to add the configure widget with the right configuration;

```javascript
search.addWidgets([
  configure({
    filters: [`id:* || $collection(id:*)`],
  })
])
```
