### ISSUE TITLE
RefinementList internal filters do not maintain

### ISSUE THREAD

**Issue by GlauberGuedes** [typesense/typesense-instantsearch-adapter#198]
## Description

Using <RefinementList /> with attribute = 'category' in algolia, when creating an internal filter in it, it kept all the filters of that facet, thus being able to click on other internal filters in it and follow the logic of operator 'or', but when I changed for typesense with 'typesense-instantsearch-adapter ', when doing this same internal filter all the filters that have no results disappeared, making it impossible to do internal 'or' filtering in the RefinementList.

Is there a setting that adjusts this?

**Typesense Version**:
"typesense-instantsearch-adapter": "^2.8.0"

**Comment by jasonbosco** [comment]
Could you elaborate on what you mean by "when creating an _internal_ filter in it"? 

If you can share a standalone repo with actual code, showing the issue, that would help.

**Comment by GlauberGuedes** [comment]
Sorry, it was my implementation error.
