### ISSUE TITLE
How to access data exposed by facet_return_parent

### ISSUE THREAD

**Issue by jfitzsimmons2** [typesense/typesense-instantsearch-adapter#204]
## Description

We have enabled facet_return_parent in the search parameters for a particular field. This is returning the data properly, but we can only see the parent field if using raw requests. Is there a way to see this information if using instantsearch/typesense instantsearch adapter?

## Steps to reproduce

facet_return_parent: 'FieldName.Property'

## Expected Behavior

I would expect this data to be exposed somewhere by the InstantSearch adapter

## Actual Behavior

All facet data and component data doesn't contain the parent data exposed by `facet_return_parent`

## Metadata

**Typesense Version**: 26

**OS**: Windows

**Comment by jasonbosco** [comment]
AFAICT, this is not possible with Instantsearch, since Algolia does not have this feature...
