### ISSUE TITLE
TypesenseInstantSearchAdapter Sends Requests to /multi_search Instead of /search and Fails to Include query_by Parameter

### ISSUE THREAD

**Issue by odean111** [typesense/typesense-instantsearch-adapter#215]
**Description**
I'm using TypesenseInstantSearchAdapter with InstantSearch.js in a Flask project to search through a jobs collection in Typesense. However, I'm encountering an issue where the adapter is sending search requests to the /multi_search endpoint instead of the /search endpoint. This happens even though I have not explicitly enabled multi_search in my configuration. Additionally, the query_by parameter is not being correctly added to the request when performing the search from the front-end.

When testing the search manually using Invoke-WebRequest (or curl), the search works correctly, returning the expected results from the /search endpoint.

**Steps to Reproduce**
Setup a Flask project using InstantSearch.js and TypesenseInstantSearchAdapter.
Create a Typesense schema for the jobs collection with fields like title, company, location, and date_posted.

Configure TypesenseInstantSearchAdapter as follows:

```
const typesenseInstantsearchAdapter = new TypesenseInstantSearchAdapter({
  server: {
    apiKey: "xyz",
    nodes: [
      {
        host: "localhost",
        port: "8108",
        protocol: "http",
      },
    ],
    cacheSearchResultsForSeconds: 2 * 60, // Cache search results
  },
  additionalSearchParameters: {
    query_by: "title"
  },
});

const searchClient = typesenseInstantsearchAdapter.searchClient;

const search = instantsearch({
  searchClient,
  indexName: "jobs",
});

search.addWidgets([
  instantsearch.widgets.searchBox({
    container: "#searchbox",
  }),
  instantsearch.widgets.hits({
    container: "#hits",
    templates: {
      item(hit) {
        return `
          <div class="hit-name">
            ${instantsearch.highlight({ attribute: 'title', hit })}
          </div>
        `;
      },
    },
  }),
  instantsearch.widgets.pagination({
    container: "#pagination",
  }),
]);

search.start();
```
Perform a search via the search bar in the front-end.

I can see in the Network tab on Chrome that the following URL is being called:

http://localhost:8108/multi_search?x-typesense-api-key=xyz

**Expected Behavior**
The search request from the front-end should be sent to the /search endpoint, with the query_by parameter included in the request. The search results should be returned from the jobs collection, filtering on the title field.

**Actual Behavior**
Instead of sending the request to the /search endpoint, the adapter is sending it to /multi_search even though no multi-index search is configured. Additionally, the query_by parameter is not being added to the request, resulting in a "No search fields specified for the query" error.

When manually testing via Invoke-WebRequest or curl, the request to /search works correctly, and the expected search results are returned from Typesense.

curl -sv "http://localhost:8108/collections/jobs/documents/search?q=developer&query_by=title" -H "X-TYPESENSE-API-KEY: xyz"

Metadata
Typesense Version: Typesense Server 0.23.1, TypesenseInstantSearchAdapter 2.3.0

**Comment by jasonbosco** [comment]
> However, I'm encountering an issue where the adapter is sending search requests to the /multi_search endpoint instead of the /search endpoint.

This is by design to avoid an extra OPTIONS (CORS) request. All searches (even single ones) are sent to the multi_search endpoint, since multi_search uses POST and we don't use any extra headers. This makes it a "Simple Request" as defined here: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#simple_requests

re: the other query_by issue, could you try running [this demo](https://github.com/typesense/typesense-instantsearch-demo) locally, modify it just enough to replicate the issue you're seeing and then share a link to your GitHub fork?

**Comment by odean111** [comment]
@jasonbosco thanks for the help! I changed "query_by" to "queryBy" and it worked. 

I copied the original code from the typesense docs: 

https://typesense.org/docs/guide/search-ui-components.html#with-a-package-manager

I think the docs might be wrong. Please see the section where it tells you that queryBy is required in the comment, but then (incorrectly?) has query_by in the code snippet. Not sure if that is something you have control over. 

```
  //  queryBy is required.
  additionalSearchParameters: {
    query_by: "title,authors"
  }
```

**Comment by jasonbosco** [comment]
Ah! I've fixed the docs. Thank you for the heads up.
