### ISSUE TITLE
refinementList selections are moving to the top of the refinementList

### ISSUE THREAD

**Issue by colmtroy** [typesense/typesense-instantsearch-adapter#217]
## Description

Assume you have a refinementList with 10 options.
Selecting option n triggers option n to move to position 1

## Steps to reproduce

Go to https://recipe-search.typesense.org/

Search for `Pineapple`
Observe position of the `Butter` option

![](https://i.imgur.com/XzHQPFB.png)

## Expected Behavior

Upon selecting `Butter` it should persist in its original position - otherwise the user loses context of what they've selected which causes confusion.

## Actual Behavior

After selecting `Butter` it jumps to the top of the refinementList

![](https://i.imgur.com/wmuhAzg.png)

Interestingly, this issue doe not occur on the main ecommerce demo
https://ecommerce-store.typesense.org/

Position of `Google` before selection.

![](https://i.imgur.com/KkOrEXd.png)

Position of `Google` after selection.

![](https://i.imgur.com/xY5sJSi.png)

Is there a special config required to have the position persist or is this a bug? I couldn't see anything obvious in the project sources to explain the difference.

**Comment by jasonbosco** [comment]
This is controlled by the sortBy parameter of refinementList: 

https://github.com/typesense/showcase-ecommerce-store/blob/03c9c0aba5111cfac47f057e073de10dfb691e2c/src/app.js#L132

**Comment by colmtroy** [comment]
@jasonbosco oh my gosh! you're correct! I could have sworn I tested that prior to creating this issue. But sure enough it works now :) Thanks for the super fast reply - I'm loving Typesense :)

**Comment by jasonbosco** [comment]
Happy to help and glad to hear that you're finding Typesense useful! 🙌
