### ISSUE TITLE
sortBy and IS routing

### ISSUE THREAD

**Issue by victorbosh** [typesense/typesense-instantsearch-adapter#23]
What is the best way to use sortBy and instantsearch.js routing?
What I'm trying is to have urls like &sort_by=price:desc filtering results and preselect sortBy widget option

**Comment by jasonbosco** [comment]
You’d just have to set routing: true when initializing instantsearch like this: https://github.com/typesense/showcase-songs-search/blob/39b3a402da0d0df4cda458daeb3909e030e3ba58/src/app.js#L158

More details [here](https://www.algolia.com/doc/guides/building-search-ui/going-further/routing-urls/js/).

**Comment by victorbosh** [comment]
I'm using https://www.algolia.com/doc/guides/building-search-ui/going-further/routing-urls/js/#seo-friendly-urls so it is not that simple :) There is createURL, parseURL, stateToRoute and routeToState works fine, but tricky with sortBy widget

**Comment by jasonbosco** [comment]
Ah yes, SEO-friendly URLs were a little not-so-straightforward to setup with InstantSearch/js, so I haven't ventured into it yet. Let me know if anything in their docs work with Algolia but not Typesense. That would indicate an issue with this adapter and I can take a closer look.

**Comment by fedex1** [comment]
@jasonbosco @victorbosh Can anyone point to a working example of somewhat search engine friendly (SEO) implementation of routing with the typesense adapter.

We'd like https://prop.tidalforce.org/elections?nys-election-details%5Bquery%5D=michael%20boomer&nys-election-details%5BsortBy%5D=nys-election-details%2Fsort%2FORG_AMTint%3Adesc 

to be more like 

https://prop.tidalforce.org/elections/nys-election-details/michael-boomer

OR

something with sorting and filtering and faceting.

There must be an example.

**Comment by jasonbosco** [comment]
The link here should work as is: https://github.com/typesense/typesense-instantsearch-adapter/issues/23#issuecomment-752206667

The adapter does not control the URL structure.
