### ISSUE TITLE
Does the adapter work with the hierarchicalMenu widget?

### ISSUE THREAD

**Issue by srconklin** [typesense/typesense-instantsearch-adapter#24]
I just came across your adapter which looks quite promising. Before I dig deeper, does it support all the Algolia InstaSearchJS widgets, specially need to confirm the hierarchicalMenu widget? 

UPDATE. Was just reviewing instant-meilisearch for comparison and they do not support  searchable facets.
[https://github.com/meilisearch/instant-meilisearch/issues/48](url)

Does this adapter support that feature? 
in fact, would this adapter be able to support all the InstantSearch features found in this demo?  (my project is basically a clone of this one) 
[https://instantsearchjs.netlify.app/examples/e-commerce/search/](url)

**Comment by jasonbosco** [comment]
Hi @srconklin!

Yes, it supports the `hierarchicalMenu` widget. You just need to have the fields in your document in a specific format like this: https://github.com/typesense/typesense-instantsearch-adapter#hierarchicalmenu

Typesense Server supports searchable facets. So you can indeed use the `searchable` of the `refinementList` widget. Here's an example showing it in action: 

https://songs-search.typesense.org/?s%5Bquery%5D=Wonderwall%20Oasis. 

If you're on mobile, you want to click on "Refine" to show the widgets. Here's the source code for the demo above: 

https://github.com/typesense/showcase-songs-search/blob/39b3a402da0d0df4cda458daeb3909e030e3ba58/src/app.js#L285-L301

> would this adapter be able to support all the InstantSearch features found in this demo?

Yes! Here's the same demo (minus the styles), but using Typesense:

Clone this repo, and then:

```
$ npm install
$ npm run typesenseServer
$ FORCE_REINDEX=true npm run indexTestData

$ npm link typesense-instantsearch-adapter
$ npm run testground
```

Now, if you open localhost:3000, you'll see all the widgets in action. 

Here's the source-code for that demo app: https://github.com/typesense/typesense-instantsearch-adapter/blob/master/test/support/testground/src/app.js

Does that help?

**Comment by srconklin** [comment]
wow!  that does help and that is awesome. I will check out the resources you list.
Thanks so much for getting back to me so quickly.

**Comment by jasonbosco** [comment]
To close the loop on this and summarize for posterity: I've extracted the testground app from this repo into its own repo here: https://github.com/typesense/showcase-ecommerce-store.

This sample code should give you an idea of how to use different InstantSearch widgets (including `hierarchicalMenu`) to build an ecommerce browsing experience: https://github.com/typesense/showcase-ecommerce-store/blob/bb450d8755903670c280bc1b31b998895a748a8f/src/app.js#L100
