### ISSUE TITLE
Routing does not work with connectInfiniteHits()

### ISSUE THREAD

**Issue by polkabrothers** [typesense/typesense-instantsearch-adapter#27]
## Description

Trying to implement infinite scroll as from this example.
[https://codesandbox.io/s/github/algolia/doc-code-samples/tree/master/InstantSearch.js/infinite-scroll](url)

Everything works but routing does not update URL when setting `route: true`.
Works as intended on the Algolia example but not in typesense-instantsearch-adapter.

I'm guessing it has something to do with using connectInfiniteHits() to create a custom infiniteHits() function?

## Steps to reproduce

Use code from [https://codesandbox.io/s/github/algolia/doc-code-samples/tree/master/InstantSearch.js/infinite-scroll](url) to implement infinite scroll with typesense-instantsearch-adapter, set `routing: true`, scroll down.

## Expected Behavior

URL should update page number when loading new items.

## Actual Behavior

URL does not update.

## Metadata

Typesense: v0.18.0
typesense-instantsearch-adapter: v0.3.4

**Comment by jasonbosco** [comment]
Hi @polkabrothers, I just used `routing: true` for the songs showcase and it worked out of the box for me: https://github.com/typesense/showcase-songs-search/blob/39b3a402da0d0df4cda458daeb3909e030e3ba58/src/app.js#L158

For example, when I type in "Wonderwall Oasis", the URL updates to: https://songs-search.typesense.org/?s%5Bquery%5D=Wonderwall%20Oasis

Are you able to share a standalone app using the InstantSearch.js Typesense adapter, where routing doesn't work?

**Comment by jasonbosco** [comment]
Also, it looks like this used to be an issue with InstantSearch.js: https://github.com/algolia/instantsearch.js/issues/3271

Could you make sure you're using the latest version of InstantSearch.js?

**Comment by polkabrothers** [comment]
Thank you for the fast reply.

Indeed it was InstantSearch.js that was the problem.
My version was 4.5.0 but I updated to 4.10.0 and now it works.

An unrelated topic, I tried to get an answer to on the Algolia community was why cssClasses does not work when using connectInfiniteHits(), using the codesandbox example above. I know it's unrelated, and it's something on Algolias end and you can close this issue now but I thought I'd just as if you had any solution to that?

Anyway, thanks for the help.

**Comment by jasonbosco** [comment]
@polkabrothers I haven't used `connectInfiniteHits` before, so I'm not 100% sure. But based on my understanding, `connectInfiniteHits` is to meant to be used to customize the rendering of the UI. So I'd image if you're rendering your own UI with it, then `cssClasses` which InstantSearch injects in its default UI wouldn't work...
