### ISSUE TITLE
Regex lookbehind in SearchRequestAdapter.js not supported in Safari

### ISSUE THREAD

**Issue by ctorgalson** [typesense/typesense-instantsearch-adapter#29]
## Description

We're seeing the following error in Safari: `SyntaxError: Invalid regular expression: invalid group specifier name`. The responsible code appears to be [the lookbehind in the regex on line 38](https://github.com/typesense/typesense-instantsearch-adapter/blob/master/src/SearchRequestAdapter.js#L38) which is [unsupported by Safari](https://caniuse.com/js-regexp-lookbehind):

```js
new RegExp("(?<!:):(?!:)")
```

## Steps to reproduce

I don't have a public test URL at the moment, but all that's necessary is to load our (complex) search which uses multiple Algolia InstantSearch widgets.

## Expected Behavior

On page load, initial search results or results modified by query string.

## Actual Behavior

On page load we see multiple instances of the error, and no results.

## Metadata

**Typsense Version**: `0.3.4`

**OS**: macOs 11.1 / iOS

**Comment by jasonbosco** [comment]
Hi @ctorgalson, I was able to replicate the issue, thank you for the pointer about the regex. I added that regex in `v0.3.2`. Could you use `v0.3.1` while I re-write that portion of the adapter?

**Comment by ctorgalson** [comment]
Thank you @jasonbosco that takes care of the immediate issue.

> ...while I re-write that portion of the adapter

I'm so sorry :grimacing:

**Comment by jasonbosco** [comment]
@ctorgalson I've published this fix in `v0.3.5`
