### ISSUE TITLE
Reduce the package size by remove the `he` dependency

### ISSUE THREAD

**Issue by DanSnow** [typesense/typesense-instantsearch-adapter#34]
## Description

Are we possible to remove the `he` and use [this method (link to Stackoverflow)](https://stackoverflow.com/a/42182294/3775132) to decode HTML entities? This could reduce the package size about 75%. This package is only for browser so this will be possible in my opinion. 

## Metadata

**Typsense Version**:

**OS**:

**Comment by jasonbosco** [comment]
@DanSnow Thank you for pointing this out. I just removed `he` as a dependency and the size went down to 13KB from 43KB!

I published this change as `v1.1.0-0`. Could you give it a shot and let me know how it goes?

**Comment by jasonbosco** [comment]
Published this in v1.1.0
