### ISSUE TITLE
Add TypeScript types

### ISSUE THREAD

**Issue by alexkreidler** [typesense/typesense-instantsearch-adapter#36]
Many frontend developers use TypeScript as well as JavaScript. 

Algolia's instantsearch packages have types, e.g: https://www.npmjs.com/package/@types/react-instantsearch-dom

It would be great to have TS types for this package. I'd imagine they are pretty simple to set up, as it the README makes it seem like the API surface is fairly small.

Thanks for this library!

**Comment by jasonbosco** [comment]
Hi @alexkreidler, this package itself does not expose any user-facing methods that you call directly. Instead, it provides a custom search client for you to pass to InstantSearch and its variants. You're still using Algolia's Instantsearch libraries directly. So you should be able to use the same types packages, even when using it with the adapter.

**Comment by alexkreidler** [comment]
Exactly, but there still is the `new TypesenseInstantSearchAdapter` function and the associated options. "fairly small" probably isn't accurate to describe one function, so my bad if I was vague there.

I'd understand if the team decides it's not worth adding the type definitions, but I'll leave this open to track it anyways.

**Comment by jasonbosco** [comment]
> I'd understand if the team decides it's not worth adding the type definitions

Oh, I'd definitely love to have Typescript definitions! Just a matter of me reading up on it and implementing it. I'd definitely welcome a PR though!
