### ISSUE TITLE
Support for server-side rendering

### ISSUE THREAD

**Issue by flavea** [typesense/typesense-instantsearch-adapter#37]
Hello, I am wondering if this adapter supports server-side rendering? Currently, our app is using findResultsState from react-instantsearch-dom/server to populate the hits on algolia instant search on server-side and I am wondering if I am switching to typesense, will it be supported? 

https://www.algolia.com/doc/guides/building-search-ui/going-further/server-side-rendering/react/#serverjs

**Comment by jasonbosco** [comment]
Hi @flavea, this adapter just provides a custom SearchClient for react-instantsearch. You're still using the original react-instantsearch library, so it _should_ work with server-side rendering as well. 

But let me know if you run into any issues.

**Comment by flavea** [comment]
@jasonbosco thank you for the answer, I tried it and it seems to be working, but I am running into problems where the queryBy field is said to be not on the schema even though I checked and there is that field in the documents, is there anything to set or check to solve this problem?

![image](https://user-images.githubusercontent.com/22873843/113974823-c55a9200-9868-11eb-9a13-e52e98975fef.png)

**Comment by jasonbosco** [comment]
Feel free to re-open if you run into any issues.
