### ISSUE TITLE
Support for operator

### ISSUE THREAD

**Issue by artt** [typesense/typesense-instantsearch-adapter#39]
## Description

Algolia's RefinementList supports [`operator`](https://www.algolia.com/doc/api-reference/widgets/refinement-list/react/#connector-param-exposed-operator) which lets you select if you want to do `and` or `or` operation. Seems like it's not supported by the adapter yet. Specifying `operator="and"` is disregarded.

**Typsense Version**: 0.19.0

**Comment by jasonbosco** [comment]
@artt @reinoldus Just addressed this in [`v1.2.1-0`](https://www.npmjs.com/package/typesense-instantsearch-adapter/v/1.2.1-0). Could you test it out and let me know how it goes?

**Comment by reinoldus** [comment]
Works! thank you!
