### ISSUE TITLE
Does This Support React Native?

### ISSUE THREAD

**Issue by stephanoparaskeva** [typesense/typesense-instantsearch-adapter#4]
Want to go further with TypeSense on my App, would like to use it in conjunction with a Search UI Widget library, is this a possibility, or what are the alternatives if not?

🚀

**Comment by jasonbosco** [comment]
@stephanoparaskeva I actually haven't tested this with React Native. Would you be open to giving it a shot and letting me know if you run into issues? 

I've love to get it to work in React Native.

**Comment by dqyu-101** [comment]
@stephanoparaskeva 
Have you tried in RN based app?
I'm trying to implement typesense in our app, but just want to see other guy's work

**Comment by jasonbosco** [comment]
@dqyu-101 Did you successfully use the adapter in React Native?

**Comment by dqyu-101** [comment]
@jasonbosco 
Not yet, I did not try the search function improvement

**Comment by arichayo** [comment]
Any update on this looking to switch from algolia

**Comment by arichayo** [comment]
It seems to be working for me! 🎉🎉🎉 Getting an error clearCache 404 not found but that doesn't seem to affect the functionality 

> @stephanoparaskeva Have you tried in RN based app? I'm trying to implement typesense in our app, but just want to see other guy's work

**Comment by jasonbosco** [comment]
Awesome, thank you confirming @arichayo! 

Could you open a separate issue for the clearCache 404 with steps to reproduce when you get a chance?

**Comment by jasonbosco** [comment]
@rmbusch The instructions for react [here](https://github.com/typesense/typesense-instantsearch-adapter#with-react-instantsearch) are identical for react-native for using this adapter. 

[Here's](https://www.algolia.com/doc/guides/building-search-ui/going-further/native/react/) react-instantsearch's guide for how to use react-instantsearch with react-native.

**Comment by rmbusch** [comment]
I am getting fatal errors that I think might have to do with native
libraries.  (I am using Expo).  I will rebuild a new dev-client and see if
that helps.

Thanks.

**Comment by prabhasg56** [comment]
@jasonbosco  I have implemented Typesense in React Native, but it is much slower compared to the web app. Could you please suggest some key points to keep in mind during development?
