### ISSUE TITLE
Is there a way to access the text_match score under the transformItems() when using Instantsearch + Typesense adapter

### ISSUE THREAD

**Issue by junelmujar** [typesense/typesense-instantsearch-adapter#56]
Hello!

I would like to know if this if  there a way to access the text_match score under the transformItems() when using Instantsearch + Typesense adapter. The purpose of this to do additional client side sorting on the results. I can see in the returned XHR result that the text_match score is returned + document fields and values. If I do console.log(items) under the transformItems() function, there is no text_match score.

Sample code below. 

	instantsearch.widgets.hits({
		container: '#hits',
		transformItems(items) {
			items.map(function(item) {
				console.log(item.text_match); // returns undefined
			});
		}
	});

Additional info:

Typsense Cloud Beta
Client: Instantsearch.js + Instantsearch Typesense adapter

**Comment by jasonbosco** [comment]
@junelmujar I just published v1.2.2-0 that adds `text_match` to all the results. Could you let me know if that works?

**Comment by junelmujar** [comment]
Hi @jasonbosco. Thanks for this mate.

I tried it today and I got this error: Uncaught ReferenceError: TypesenseInstantsearchAdapter is not defined...

I also got the same error yesterday when I did my own build of the library with my changes.

<script src="https://cdn.jsdelivr.net/npm/instantsearch.js@4.20.0/dist/instantsearch.production.min.js"></script>
<script src="typesense-instantsearch-adapter.min.js"></script>

**Comment by jasonbosco** [comment]
Looks like there's a typo - the `S` in InstantSearch needs to capitalized. So you want to do `new TypesenseInstantSearchAdapter`

**Comment by junelmujar** [comment]
Confirming that it's working now. Thanks a lot @jasonbosco 👍
