### ISSUE TITLE
How to add structured results for typesense?

### ISSUE THREAD

**Issue by anooj-gandham** [typesense/typesense-instantsearch-adapter#62]
## Description

We are trying to add structured results like the extra information displayed apart from query results by search engines like Google, Bing and DuckDuckGo.

![image](https://user-images.githubusercontent.com/63911217/126076636-d3193690-a7aa-420d-a472-b043eef5db1f.png)

## Steps to reproduce

We followed the documentation from Algolia for the InstantSearch for building this feature.
Documentation:  https://www.algolia.com/doc/guides/building-search-ui/ui-and-ux-patterns/structured-results/js/?client=js
Demo Example: https://github.com/algolia/demo-structured-result

We have added two seperate collections to the typesense server as main_index and structured_index.
We modified the initialization of instantsearch client to accomodate the typesense server.

## Problem
An error occurs stating `Could not find a field name <field name> in the schema`.

Any suggestions would be helpful in this regards.

## Metadata

**Typsense Version**:
Latest
**OS**:
Ubuntu 20

**Comment by jasonbosco** [comment]
@anooj-gandham Could you post both collections’ schema, and the Typesense instantsearch adapter configuration you’re using?

**Comment by anooj-gandham** [comment]
MAIN INDEX: 
name: "products",
    fields: [
      { name: "name", type: "string" },
      { name: "category", type: "string", facet: true },
      { name: "url", type: "string" },
      { name: "description", type: "string" },
      { name: "text", type: "string" },
      { name: "price", type: "int32", facet: true },
      ]

STRUCTURED INDEX:
name: 'product_brand',
    fields: [
      { name: 'text', type: 'string' },
      { name: 'url', type: 'string' },
    ]


const typesenseInstantsearchAdapter = new TypesenseInstantSearchAdapter({
  server: {
    apiKey: "xyz",
    nodes: [
      {
        host: "localhost",
        port: "8108",
        protocol: "http",
      },
    ],
  },
  additionalSearchParameters: {
    queryBy: "text,name",
    highlightAffixNumTokens: 20, // 
  },
});

**Comment by jasonbosco** [comment]
Ah, the reason you're seeing the error is because you've set `name` in `additionalSearchParameters.queryBy`, but that field doesn't exist in structured index. 

You want to use `collectionSpecificSearchParameters` to specify different `queryBy` values for each collection, as described here: https://github.com/typesense/typesense-instantsearch-adapter/blob/master/README.md#index

**Comment by anooj-gandham** [comment]
After making changes as mentioned above, now I am getting this error.

`"Uncaught Error: Missing required parameter: additionalSearchParameters.queryBy"`

What should be done?

**Comment by jasonbosco** [comment]
Could you post your updated adapter configuration?

**Comment by anooj-gandham** [comment]
```
const typesenseInstantsearchAdapter = new TypesenseInstantSearchAdapter({
  server: {
    apiKey: "xyz", // Be sure to use an API key that only allows search operations
    nodes: [{ host: "localhost", port: "8108", protocol: "http" }],
  },
  // Search parameters that are common to all collections/indices go here:
  additionalSearchParameters: {
    numTypos: 3,
    // queryBy: "text",
  },
  // Search parameters that need to be *overridden* on a per-collection-basis go here:
  collectionSpecificSearchParameters: {
    products: {
      queryBy: "name",
    },
    product_brand: {
      queryBy: "text",
    },
  },
});
```

**Comment by jasonbosco** [comment]
It looks like you might be using an older version of the adapter which didn't support `collectionSpecificSearchParameters`. Could you upgrade to the latest version and try again?

**Comment by cssistoughestthingihaveeverdone** [comment]
We  downloaded latest typesense (10 days ago) and used it.  (I am working with the issue reporter). Is there a newer version?

**Comment by jasonbosco** [comment]
Please feel free to re-open this issue if you're still running an issue.
