### ISSUE TITLE
Error when i import TypesenseInstantSearchAdapter

### ISSUE THREAD

**Issue by hoanam2k2** [typesense/typesense-instantsearch-adapter#64]
## Description
![Capture](https://user-images.githubusercontent.com/74503155/128328579-ab0a158c-a505-45b1-bafb-d66d6fe1ad37.PNG)

i had install npm
npm install algoliasearch@3 angular-instantsearch@beta instantsearch.js@3 instantsearch.css
npm install --save-dev @types/algoliasearch
and add module NgAisModule 
## Metadata

**Typsense Version**:

**Comment by jasonbosco** [comment]
@hoanam2k2 That's just a warning that says Typescript types are not available for this library. It's safe to ignore. 

Typescript types are being added as part of #36.
