### ISSUE TITLE
snippeting with multiple matches

### ISSUE THREAD

**Issue by bnfd** [typesense/typesense-instantsearch-adapter#69]
In instantsearch.js we can use `attributesToSnippet: ["content:50"]` to return a part of the matched attribute. In cases where there are multiple matches (multiple occurrences of the keyword) in the same record, only one will be returned.
Is there a way to return all of them?

**Comment by jasonbosco** [comment]
@bnfd The typesense-instantsearch-adapter automatically enables full-field highlights for you, which returns all matchces. You just want to use the `highlights` helper like this to display all matches in the UI: 

https://github.com/typesense/showcase-ecommerce-store/blob/5cf0597807da2429af00a73c1c2e69fe6bd3fafb/src/app.js#L207
