### ISSUE TITLE
problem with get data in typesense 

### ISSUE THREAD

**Issue by jonatasoli** [typesense/typesense-instantsearch-adapter#72]
## Description

I have a problem with use the lib with vue3, I use the js lib with vue2 and found.

## Steps to reproduce

Old project
https://github.com/agucova/regulf-neo

New project
https://github.com/jonatasoli/regulf-neo-v3

## Expected Behavior

The old project is found correct and list the result, but project with vue3 is raise error:
TypesenseInstantsearchAdapter.js?7ea0:76 Error: Request failed with HTTP code 401 | Server said: Forbidden - a valid `x-typesense-api-key` header must be sent.

## Actual Behavior

Run the server and enter in home page, is found.

Old project:
npm start

new project:
npm serve

## Metadata

**Typsense Version**:
0.11.0

**OS**:
Fedora 34

**Comment by jasonbosco** [comment]
Could you use the latest version of Typesense and Typesense adapter just to be sure?

**Comment by jonatasoli** [comment]
Hello @jasonbosco I try update older project the typesense-instantsearch-adapter to new version and app continue working.

**Comment by jasonbosco** [comment]
@jonatasoli I meant, could you try updating Typesense and Typesense adapter in the newer version of the project.

**Comment by jonatasoli** [comment]
Hello I updated but the same problem.

**Comment by jasonbosco** [comment]
@jonatasoli In the old app it looks like you're using `revenue_entry` as the collection name: 

https://github.com/agucova/regulf-neo/blob/4c97fe6ef80983318bf63a60b197ee9cbfab9fbd/src/app.js#L28

But in the new app you're using `results` as the collection name:

https://github.com/jonatasoli/regulf-neo-v3/blob/9f6c432e990b8a3e449ae574c20e78ba271c23a3/src/views/Home.vue#L5

If you change `results` to `revenue_entry` in the new app, it seems to work fine.

**Comment by jonatasoli** [comment]
Really this is the problem I change result and found, thanks for helping
