### ISSUE TITLE
Algolia hitsPerPage is not honored

### ISSUE THREAD

**Issue by redochka** [typesense/typesense-instantsearch-adapter#73]
## Description

Using typesense with the instantsearch.js and trying to limit the number of results displayed per page

## Steps to reproduce

instantsearch.widgets.configure({
  hitsPerPage: 4,
  enablePersonalization: true,
});

## Expected Behavior

Display 4 items

## Actual Behavior

displays 10 items per page

## Metadata

**Typsense Version**: 0.20.0

**OS**: linux

**Comment by jasonbosco** [comment]
Hmm, that should work. I've used it exactly like this before: https://github.com/typesense/showcase-recipe-search/blob/7a9396a76fbfc4b749531fc34546fa92ba654b10/src/app.js#L301-L303

Could you share a minimal app to reproduce this behavior?

**Comment by redochka** [comment]
Got it. Thanks for sharing the link.

```
// Wrong place
instantsearch.widgets.configure({
  hitsPerPage: 4,
  enablePersonalization: true,
}),
  
search.addWidgets([

  //The configure is a widget, so it needs to put be here ...
  
  instantsearch.widgets.searchBox({...}),
  instantsearch.widgets.hits({...}),
  instantsearch.widgets.pagination({...}),
])
```
Sorry for the disturbance. Now it works.
