### ISSUE TITLE
how i can set setting

### ISSUE THREAD

**Issue by huynv86** [typesense/typesense-instantsearch-adapter#80]
could you please give me an instruction for

https://www.algolia.com/doc/guides/managing-results/refine-results/faceting/how-to/declaring-attributes-for-faceting/#using-the-api

I want to make initial value for Typesense

**Comment by jasonbosco** [comment]
In Typesense, you can enable a field for faceting in the collection's schema. More info here: https://typesense.org/docs/0.22.1/api/collections.html#schema-arguments
