### ISSUE TITLE
Typescript, what Type of additionalSearchParameters

### ISSUE THREAD

**Issue by huynv86** [typesense/typesense-instantsearch-adapter#86]
![image](https://user-images.githubusercontent.com/747614/148076592-e791de6f-c5a3-4b5c-b20c-7c2df55fb712.png)
I don't want to set this property is Type 'any'

**Comment by jasonbosco** [comment]
@huynv86 I just published v2.4.0-0 which adds more concrete types to additionalSearchParameters. Could you give it a shot now?
