### ISSUE TITLE
error 404 at TypesenseInstantsearchAdapter._validateTypesenseResult

### ISSUE THREAD

**Issue by ibasaw** [typesense/typesense-instantsearch-adapter#89]
hi,

typesense:0.21.0
"typesense-instantsearch-adapter": "^2.2.0"
"instantsearch.js": "^4.37.2",

linux ubuntu

i got algolia instantsearch installed ok, and work fine

when i want to use the adapter, i got this error in console and no hit appear  on web view:

`DevTools failed to load source map: Could not load content for https://cdn.jsdelivr.net/npm/instantsearch.production.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
TypesenseInstantsearchAdapter.js:76 Error: 404 - Not found.
    at TypesenseInstantsearchAdapter._validateTypesenseResult (TypesenseInstantsearchAdapter.js:173:1)
    at TypesenseInstantsearchAdapter.js:64:1
    at Array.map (<anonymous>)
    at TypesenseInstantsearchAdapter._callee$ (TypesenseInstantsearchAdapter.js:63:1)
    at tryCatch (runtime.js:63:15)
    at Generator.invoke [as _invoke] (runtime.js:294:1)
    at Generator.next (runtime.js:119:1)
    at asyncGeneratorStep (asyncToGenerator.js:3:1)
    at _next (asyncToGenerator.js:25:1)
_callee$ @ TypesenseInstantsearchAdapter.js:76
tryCatch @ runtime.js:63
invoke @ runtime.js:294
(anonymous) @ runtime.js:119
asyncGeneratorStep @ asyncToGenerator.js:3
_next @ asyncToGenerator.js:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
searchTypesenseAndAdapt @ TypesenseInstantsearchAdapter.js:88
search @ TypesenseInstantsearchAdapter.js:38
./node_modules/algoliasearch-helper/src/algoliasearch.helper.js.AlgoliaSearchHelper._search @ algoliasearch.helper.js:1270
./node_modules/algoliasearch-helper/src/algoliasearch.helper.js.AlgoliaSearchHelper.searchOnlyWithDerivedHelpers @ algoliasearch.helper.js:154
mainHelper.search @ InstantSearch.js:389
(anonymous) @ InstantSearch.js:108
(anonymous) @ defer.js:24
Promise.then (async)
fn @ defer.js:16
start @ InstantSearch.js:464
./themes/default-theme/assets/js/index.js @ index.js:46
__webpack_require__ @ bootstrap:19
./themes/default-theme/assets/app.js @ app.js:11
__webpack_require__ @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ bootstrap:83
TypesenseInstantsearchAdapter.js:173 Uncaught (in promise) Error: 404 - Not found.
    at TypesenseInstantsearchAdapter._validateTypesenseResult (TypesenseInstantsearchAdapter.js:173:1)
    at TypesenseInstantsearchAdapter.js:64:1
    at Array.map (<anonymous>)
    at TypesenseInstantsearchAdapter._callee$ (TypesenseInstantsearchAdapter.js:63:1)
    at tryCatch (runtime.js:63:15)
    at Generator.invoke [as _invoke] (runtime.js:294:1)
    at Generator.next (runtime.js:119:1)
    at asyncGeneratorStep (asyncToGenerator.js:3:1)
    at _next (asyncToGenerator.js:25:1)`

**Comment by jasonbosco** [comment]
@ibasaw The 404 error sounds like there might be typo in the index / collection name in the instantsearch adapter configuration. Could you double-check the network request and make sure the collection name in the API call is as expected.

**Comment by ibasaw** [comment]
my config is good, because it works with algolia instantsearch.js javascript version

**Comment by jasonbosco** [comment]
@ibasaw To debug this further, could you open the network tab in the browser's dev tools, recreate the error you see in the console, and then look for requests to Typesense that show a 404 in the network tab. Right-click on that request, copy-as-curl and paste it here. 

Could you also share the instantsearch adapter configuration and instantsearch widget code you're using?

**Comment by ibasaw** [comment]
```
curl 'http://172.20.0.9:8108/multi_search?x-typesense-api-key=xyz' \
  -H 'Connection: keep-alive' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36' \
  -H 'Content-Type: text/plain' \
  -H 'Origin: http://dev-sylius.com:8091' \
  -H 'Referer: http://dev-sylius.com:8091/' \
  -H 'Accept-Language: fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7' \
  --data-raw '{"searches":[{"query_by":"code","sort_by":"","highlight_full_fields":"code","collection":"products","q":"*","facet_by":"","page":1}]}' \
  --compressed \
  --insecure
```

**Comment by ibasaw** [comment]
```
curl http://172.20.0.9:8108/health
{"ok":true}
```

**Comment by jasonbosco** [comment]
@ibasaw I see the name of the collection is "product" (singular), but in the curl request the collection name is "products" (plural). You want to use the Typesense collection name as the index name when instantiating instant search.

**Comment by ibasaw** [comment]
i need better glasses, thank you @jasonbosco !
