### ISSUE TITLE
additionalSearchParameter -> 'q' or 'query' not respected

### ISSUE THREAD

**Issue by zopyx** [typesense/typesense-instantsearch-adapter#92]
I want to try to issues:

- Typesense should not display any hit without a given query. So the default search page should display the search box by default, display hits for a given query in the search field.
- I want to pass a parameter with a text query to the search and the generated search form should display the query within the search form and display immediately the related hits.

This does not work:

```
    additionalSearchParameters: {
        queryBy: ts_settings["query_by"],
        filterBy: filterBy,
        q: "foo"
    },

```

I also tried `query` instead of `q`.

**Comment by jasonbosco** [comment]
Instantsearch controls the value for the `q` parameter, so you'll have to use instantsearch to do this. 

Here's an example of how to do this: https://github.com/typesense/showcase-songs-search/blob/9b2d91ab5e3a16480b93de5ae103bf9969f58ac5/src/app.js#L159-L166

You'll see this in action here: https://songs-search.typesense.org/
