### ISSUE TITLE
Updating additionalSearchParameters after initializing TypesenseInstantSearchAdapter

### ISSUE THREAD

**Issue by seowzhenjun0126** [typesense/typesense-instantsearch-adapter#99]
## Description

Hi,

I am trying to optimize the size of returned data from user's query to display in a table. One of the ways that I thought of is to only return the fields that the user chooses to display in the table by using the `include_fields` parameter.

However, a user may update the columns to display (i.e. hiding or showing a column) when using the app, and so the `include_fields` parameter should be updated as well.

Is there any way I can achieve this?

Thanks!

## Metadata

**Typsense Version**: 2.4.0

**OS**: Windows 11

**Comment by jasonbosco** [comment]
@seowzhenjun0126 One way you could do this is by instantiating a new instance of the adapter once your user has chosen the columns to display, instead of instantiating the adapter at page load.
